### ISSUE TITLE
Complete Sentinel Golang Code Specification

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#100]
## Issue Description

Type: *feature request*

### Describe what feature you want
1. Complete code specifications wiki;
2. Based on code specifications to refine all code.

Including:
1. Log standardization
2.Comments standardization
3.Code Related.
4. Format(using  go fmt)
5. Pr  standardization.

**Comment by sczyh30** [comment]
For reference:

- https://golang.org/doc/effective_go.html
- https://github.com/golang/go/wiki/CodeReviewComments

**Comment by luckyxiaoqiang** [comment]
Another reference:  
https://github.com/uber-go/guide/blob/master/style.md

**Comment by louyuting** [comment]
duplicated to #367
