### ISSUE TITLE
[BUG]add len(items) > 0 for getLatestSecond function

### ISSUE THREAD

**Issue by zsy619** [alibaba/sentinel-golang#108]
## Issue Description

Type: *bug report*

### Describe what happened
add test method happend：
panic: runtime error: index out of range [-1] [recovered]
	panic: runtime error: index out of range [-1]

### Describe what you expected to happen
test code：
make param items equals []*base.MetricItem{}

### Anything else we need to know?
modify ：
if items == nil {
		return 0
	}
to：
if items == nil  || len(items) == 0{
		return 0
	}

**Comment by louyuting** [comment]
Fixed by https://github.com/alibaba/sentinel-golang/pull/121
