### ISSUE TITLE
Improve documents

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#110]
## Issue Description

Type: *feature request*

### Describe what feature you want
Prefect wiki in [https://github.com/sentinel-group/sentinel-website/tree/master/docs/zh-cn/golang](https://github.com/sentinel-group/sentinel-website/tree/master/docs/zh-cn/golang)

Including items:

Main Content:

- [x] Overall introduction
- [x] Usage guides
- [x] Flow control
- [x] Circuit breaking
- [x] isolation control
- [x] System adaptive flow control
- [x] hotspot flow control
- [x] General configuration
- [x] Logging
- [x] Dynamic data source extension

**Comment by louyuting** [comment]
@sanxun0325  Do you have effort on this issue?

**Comment by sanxun0325** [comment]
I'll try

**Comment by louyuting** [comment]
Nice

**Comment by sczyh30** [comment]
The website page (CN) of Sentinel Go has been generated: https://sentinelguard.io/zh-cn/docs/golang/basic-api-usage.html
