### ISSUE TITLE
Add value cache/checking mechanism for rule managers

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#111]
## Issue Description

Type: *feature request*

### Describe what feature you want
In order to avoid the meaningless updates to the property, downstream of property manager should 
cache last update value to check consistency.

**Comment by hellosmallstone** [comment]
I will try to implement this function.
Please assign this to me.

**Comment by louyuting** [comment]
Contributions are welcomed

**Comment by louyuting** [comment]
@hellosmallstone  Hi, any process?

**Comment by sanxun0325** [comment]
This issue can be assigned to me! I will resolve it.

**Comment by louyuting** [comment]
Welcomed~

**Comment by sczyh30** [comment]
Resolved via #253, #321, #322, #324. Cheers! 🚀 
We may need a universal design after 1.0 GA.
