### ISSUE TITLE
Refactor the rulemanager

### ISSUE THREAD

**Issue by chenjiandongx** [alibaba/sentinel-golang#112]
## Issue Description

Type: *feature request*

#### * Use ThreadSafe map to replace the official map.

In previous code design, the map isn't threadsafe, and we should use lock every map operation.

So, why don't we create a new safe map type for it?

In particular, I rename `TrafficControllerMap` to `TrafficControllers`, because I think that it's unnecessary to name a variable with its type. 

There is an article taking about it https://dave.cheney.net/2019/01/29/you-shouldnt-name-your-variables-after-their-types-for-the-same-reason-you-wouldnt-name-your-pets-dog-or-cat

**Comment by louyuting** [comment]
In fact, current code is thread safe.
Refer to 
https://github.com/alibaba/sentinel-golang/blob/9d5bff9aa91e1855e8b16f4b0ce10d29c9a3b4ae/core/flow/rule_manager.go#L25

Sentinel use RWMutex to lock the `tcGenFuncMap` and `tcMap`.

**Comment by chenjiandongx** [comment]
After rethinking your review feedbacks, as you said, It does look a little over design.

because golang has its own `sync.Map` struct, so I just want to give it a type clear safe map at that time. It's ok for me to close this PR.

but there still some details could be optimize, such as 

https://github.com/alibaba/sentinel-golang/blob/9d5bff9aa91e1855e8b16f4b0ce10d29c9a3b4ae/core/flow/rule_manager.go#L213-L228

It's unnecessary to return nil in a switch case at this code snippet.
