### ISSUE TITLE
Support default circuit breaking rule for all resources

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#132]
## Issue Description

Type: *feature request*

### Describe what feature you want
Currently, user should add rules for all resource even if the rules are the same.

Sentinel should support common rules for all resource.

**Comment by sanxun0325** [comment]
This issue can be assigned to me! I will resolve it.

**Comment by louyuting** [comment]
Welcomed

**Comment by louyuting** [comment]
The proposal might be unreasonable, the resource level replacement might be better.
