### ISSUE TITLE
Organize imports in groups

### ISSUE THREAD

**Issue by hellosmallstone** [alibaba/sentinel-golang#135]
## Issue Description
In the project, imports are organized in a group, which seems to be disorganized. And the CodeReviewComments suggests "Imports are organized in groups, with blank lines between them. The standard library packages are always in the first group.". For a detailed description, please refer to https://github.com/golang/go/wiki/CodeReviewComments#imports.

Type: *feature request*

### Describe what feature you want
We can perform a unified process on the current code, and we should abide by this rule when reviewing the code later, in order to achieve a unified style.

**Comment by hellosmallstone** [comment]
@sczyh30 @louyuting Do you have any objections to this suggestion? If you agree that the project sentinel-golang also adopts the imports style, I will complete the modification of the existing code as soon as possible.

**Comment by sczyh30** [comment]
Good suggestion. Feel free to submit a PR to improve this. And maybe we need to add checking in CI.
