### ISSUE TITLE
NewTokeResult exist a performance problem，recommended sync.pool

### ISSUE THREAD

**Issue by NineSunRD** [alibaba/sentinel-golang#137]
![image](https://user-images.githubusercontent.com/13688621/80175867-743a9980-8629-11ea-9c4e-6e808d977b0c.png)

**Comment by louyuting** [comment]
Hi @NineSunRD 
Your advice is very helpful. Could you please contribute for this issue?
Waiting for your amazing PR.
Thanks.

**Comment by NineSunRD** [comment]
It is my pleasure to contribute for this issue.
I will use my spare time to contribute for this issue.
Thanks.

**Comment by louyuting** [comment]
Done, refer to PR: https://github.com/alibaba/sentinel-golang/pull/142
