### ISSUE TITLE
Improve the sync.Pool of TokenResult and EntryContext

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#144]
## Issue Description

Type: *feature request*

**Comment by louyuting** [comment]
@NineSunRD  We might need to enhance the sync.Pool usage for TokenResult and EntryContext.
Are you interesting in this issue?

**Comment by NineSunRD** [comment]
I will try it

**Comment by louyuting** [comment]
There is a DATA RACE BUG in previous PR: https://github.com/alibaba/sentinel-golang/pull/142.

It caused by using TokenResult after refurbishing.

The detail and  fix PR refer to: https://github.com/alibaba/sentinel-golang/pull/149

**Comment by louyuting** [comment]
Refer to https://github.com/alibaba/sentinel-golang/pull/149
I will close this issue,
Any good idea please reach to me.
Thanks.
