### ISSUE TITLE
How to configure distributed flow control with Sentinel dashboard?

### ISSUE THREAD

**Issue by xmge** [alibaba/sentinel-golang#146]
## Issue Description

在example和wiki中没有找到如何进行分布式的流控，只找到了单节点的流控。有相关的文档的说明吗？如何通过 dashboad进行控制流控规则呢

**Comment by sczyh30** [comment]
Distributed flow control and dashboard integration have not been supported yet in Sentinel Go. We might introduce these features in upcoming releases. Contributions are welcomed!

**Comment by xmge** [comment]
e ....ok!

**Comment by sysublackbear** [comment]
现在支持了吗？分布式限流
