### ISSUE TITLE
Split adapter to independent repo

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#158]
# Issue Description

Type: *feature request*

### Describe what feature you want

- [x] dubbo-go

- [x] gin

- [x] micro

- [x] echo

- [x] grpc

**Comment by DogBaoBao** [comment]
Look like com/alibaba/csp/sentinel/adapter/dubbo in java?

**Comment by DogBaoBao** [comment]
How sentinel do automatic streaming when Dubbo under the cloud native ?

**Comment by sczyh30** [comment]
> How sentinel do automatic streaming when Dubbo under the cloud native ?

Could you please illustrate your question?

**Comment by sczyh30** [comment]
For dubbo-go integration, we may open an issue in dubbo-go repo.

**Comment by louyuting** [comment]
add sentinel-go to dubbo-go, refer to : [https://github.com/apache/dubbo-go/pull/748](https://github.com/apache/dubbo-go/pull/748)

**Comment by sczyh30** [comment]
Adapters have been moved to https://github.com/sentinel-group/sentinel-go-adapters
