### ISSUE TITLE
[BUG] go.mod versioned 1.13, but go1.12 checking is configured in travis-ci

### ISSUE THREAD

**Issue by gorexlv** [alibaba/sentinel-golang#159]
## Issue Description

go.mod required go 1.13, but go1.12 checking is configured in travis-ci.

Some go1.13 features, such as errors.Is, will fail in unit testing.

Backward compatibility needs to be clarified, go1.12 or older / go1.13 or later?

Type: *bug report*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by louyuting** [comment]
@sczyh30 
What do you think of deleting golang 1.12 support in travis-ci?

**Comment by sczyh30** [comment]
> @sczyh30
> What do you think of deleting golang 1.12 support in travis-ci?

That's okay.

**Comment by louyuting** [comment]
@gorexlv   Could you please file a PR to fix this issue?

**Comment by gorexlv** [comment]
90a8d99c9 fixed this issue

@louyuting @sczyh30

**Comment by sczyh30** [comment]
Resolved in #116
