### ISSUE TITLE
InitDefault may fail if no HOME env (while using supervisor)

### ISSUE THREAD

**Issue by absolute8511** [alibaba/sentinel-golang#165]
As mentioned in the supervisor document (http://supervisord.org/subprocess.html#subprocess-environment), the `HOME` may not be set, so the `InitDefault` which will try init log dir with `HOME` will fail to init.  It is very tricky to use `HOME` as the default dir, I think maybe the OS temp dir should be used as default instead of the `HOME` dir.

https://github.com/alibaba/sentinel-golang/blob/c37b472e97de7691a566e078dae3f1a9ed73536d/core/config/config.go#L144

```
func InitDefault() error {
	return initSentinel("")
}

func initSentinel(configPath string) (err error) {
	defer func() {
		if r := recover(); r != nil {
			var ok bool
			err, ok = r.(error)
			if !ok {
				err = fmt.Errorf("%v", r)
			}
		}
	}()
	// Initialize general config and logging module.
	if err = config.InitConfig(configPath); err != nil {
		return err
	}
	return initCoreComponents()
}
```

**Comment by louyuting** [comment]
From my perspective,  the log file(record log / metric monitor log) is very important for sentinel.
Using the OS temp directory to store log file does not make sense.

Maybe we should provide a way to set logging directory?

Discussions are welcomed.

**Comment by absolute8511** [comment]
If it is very important then maybe it should not be allowed to leave it as default.

**Comment by louyuting** [comment]
@sczyh30  How do you think about?

**Comment by sczyh30** [comment]
> @sczyh30 How do you think about?

It's already supported to set the logging directory via system env or YAML file. Refer: https://github.com/alibaba/sentinel-golang/wiki/通用配置项

**Comment by absolute8511** [comment]
> > @sczyh30 How do you think about?
> 
> It's already supported to set the logging directory via system env or YAML file. Refer: [https://github.com/alibaba/sentinel-golang/wiki/通用配置项](https://github.com/alibaba/sentinel-golang/wiki/%E9%80%9A%E7%94%A8%E9%85%8D%E7%BD%AE%E9%A1%B9)

What we discuss is how to make sure the default can work with no error in all cases.

**Comment by louyuting** [comment]
@absolute8511  From my perspective, **HOME** as default log dir is okay.
In other word, we could set log file path by yaml config file or manually setting.
Do you have any other concern?

**Comment by louyuting** [comment]
Closed B/C no updates.
Any update please reopen the issue
