### ISSUE TITLE
Use linters to guarantee code quality.

### ISSUE THREAD

**Issue by cncal** [alibaba/sentinel-golang#169]
## Issue Description

Type: *feature request*

### Describe what feature you want

In the rapid development stage of the project, many code will be contributed to it and different contributors have different coding styles. So I think we should add linters to CI as soon as possible to guarantee the code quality. These linters include but are not limited to:
* vet
* staticcheck
* errcheck
* ...

**Comment by louyuting** [comment]
That sounds wonderful.
Could you please file a PR to enhance?

**Comment by louyuting** [comment]
Per https://github.com/alibaba/sentinel-golang/pull/170
