### ISSUE TITLE
Add "warm-up" control behavior support

### ISSUE THREAD

**Issue by sczyh30** [alibaba/sentinel-golang#177]
## Issue Description

Type: *feature request*

### Describe what feature you want

Add "warm-up" control behavior support.

Refer: https://github.com/alibaba/Sentinel/wiki/Flow-Control:-Warm-Up

**Comment by DogBaoBao** [comment]
I can try this.

**Comment by louyuting** [comment]
Welcomed.
Looking forward to your design and PR

**Comment by sczyh30** [comment]
> I can try this.

Hi, any progress?

**Comment by sanxun0325** [comment]
I can try this.

**Comment by sczyh30** [comment]
Please note that the warm-up factor may be configured in `FlowRule`.

**Comment by DogBaoBao** [comment]
> > I can try this.
> 
> Hi, any progress?

Sorry, I went outing. There was no Internet in some days and no times for focus on. I see other is done this issue, thanks for  sanxun0325.

**Comment by sczyh30** [comment]
@DogBaoBao You may help to review the PR together :)
