### ISSUE TITLE
Confusion about LeapArray.calculateTimeIdx().

### ISSUE THREAD

**Issue by cncal** [alibaba/sentinel-golang#180]
# Describe what happened 

This is a leapArray example(copied from [alibaba/Sentinel](https://github.com/alibaba/Sentinel/blob/57f9bc7a6a67e95e57de2611702993ff95d65d5f/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/LeapArray.java#L156)):
``` java
     B0       B1      B2     B3      B4
||_______|_______|_______|_______|_______||___
200     400     600     800     1000    1200  timestamp
                            ^
                        time=888
```

In this leapArray:
```
bucketLengthInMs = 200;
sampleCount = 5;
intervalInMs = 1000
```
If `time` is 888,  it should be in bucket with index 3. But `calculateTimeIdx()` return 4. Am I misunderstanding something?

**Comment by louyuting** [comment]
> # Describe what happened
> This is a leapArray example(copied from [alibaba/Sentinel](https://github.com/alibaba/Sentinel/blob/57f9bc7a6a67e95e57de2611702993ff95d65d5f/sentinel-core/src/main/java/com/alibaba/csp/sentinel/slots/statistic/base/LeapArray.java#L156)):
> 
> ```java
>      B0       B1      B2     B3      B4
> ||_______|_______|_______|_______|_______||___
> 200     400     600     800     1000    1200  timestamp
>                             ^
>                         time=888
> ```
> 
> In this leapArray:
> 
> ```
> bucketLengthInMs = 200;
> sampleCount = 5;
> intervalInMs = 1000
> ```
> 
> If `time` is 888, it should be in bucket with index 3. But `calculateTimeIdx()` return 4. Am I misunderstanding something?

Not sure how to handle this case in java. In golang version, if the time is 888, the index in sliding windows is 4, this time will target in last slot. 

For example. when sentinel runs, current time is 1000, sentinel go will build sliding windows below:
```
>      B0       B1      B2     B3      B4
>  |_______|_______|_______|_______|
> 200     400     600     800     1000
```

with time goes by, the coming time will be greater than 1000. For example, time is 1008, will update the sliding windows below:
```
>      B0       B1      B2     B3      B4
>  |_______|_______|_______|_______|
> 1000     400     600     800     1000
```
with 1 second goes by(Suppose there's traffic going on all the time), the sliding window will be updated to the following status
```
>      B0       B1      B2     B3      B4
>  |_______|_______|_______|_______|
> 1000     1200    1400   1600   1800
```

**Comment by cncal** [comment]
So `calculateTimeIdx()` makes no sense for the time before this slide window is built !?

**Comment by louyuting** [comment]
I think `calculateTimeIdx()` make sense. It is possible that building a sliding window ahead of time leads to misunderstandings .

**Comment by cncal** [comment]
Assuming sentinel works and a slide window is built at 1000, if I calculate time idx of 888(in fact, it couldn't happen), 4 would returned. But as we see from the timeline, 888 should be slotted in 3 (800~1000). It's confusing me.

**Comment by sczyh30** [comment]
@cncal The description in comments of Java LeapArray might be confusing. For this case:

```
||_______|_______|_______|_______|_______||___
200     400     600     800     1000    1200  timestamp
                            ^
                        time=888
```

The actual layout of internal array is:

```
||_______|_______|_______|_______|_______||
1200    200     400     600     800     1000  timestamp
                                    ^
                                  time=888
```

So the actual index (of the array) is 4.
