### ISSUE TITLE
Initialize ruleManager how to read configuration

### ISSUE THREAD

**Issue by sanxun0325** [alibaba/sentinel-golang#189]
## Issue Description
I want to read the configuration file in the Rulemanager.go init func
Type: *feature request*

### Describe what feature you want
I want to read the configuration file in the Rulemanager.go init func
### Additional context

![image](https://user-images.githubusercontent.com/28588342/88407410-a912e400-ce04-11ea-9439-0ac11c2fef76.png)

**Comment by louyuting** [comment]
@sanxun0325  Could you describe the scenario why need this feature?

**Comment by louyuting** [comment]
After communicating, solve this issue by yaml config file.
