### ISSUE TITLE
Improve the default JSON rule parsers in ext/datasource package

### ISSUE THREAD

**Issue by sczyh30** [alibaba/sentinel-golang#191]
## Issue Description

Type: *improvement*

### Describe what feature you want

The default JSON rule parsers in `ext/datasource` package could be improved. In current implementation, even if the JSON itself is not an array of flow rule entities, empty `FlowRule` might be generated:

https://github.com/alibaba/sentinel-golang/blob/1f1c71b99daafc10ebca124749047d28ed6904b0/ext/datasource/helper.go#L32-L51

Though the empty entity will be filtered out when pumping it to downstream consumers, the creation of the "invalid" entity seems useless. In addition, it might be better to leverage the unified quotes of the fields (aka. `json:"xxx"`) to parse the object instead of writing the logic manually.

The naming could be improved as well. For example: `FlowRulesJsonConverter` can be `FlowRuleJsonArrayParser` or other better.

**Comment by sanxun0325** [comment]
I'll try to work it out

**Comment by sczyh30** [comment]
cc @louyuting Any suggestions?

**Comment by louyuting** [comment]
>In current implementation, even if the JSON itself is not an array of flow rule entities, empty FlowRule might be generated:

Maybe we could check the validity after parsing entity.

Naming improvement make sense.
