### ISSUE TITLE
go test Test_listMetricFiles faild and TestNewFileDataSource_ALL_For_SystemRule_Write_Event faild

### ISSUE THREAD

**Issue by sanxun0325** [alibaba/sentinel-golang#194]
## Issue Description
os: win10
Run locally： go test -race  -count=1 ./...

![image](https://user-images.githubusercontent.com/28588342/88870506-1af58e00-d248-11ea-924f-2c07c62b731b.png)

**Comment by sanxun0325** [comment]
I'll try to work it out

**Comment by sczyh30** [comment]
Fixed in #195
