### ISSUE TITLE
Adapt to the dashboard of Java version

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#20]
## Issue Description
sentinel will reuse the dashboard of java version.

**Comment by syncwt** [comment]
When will the version be supported probably?

**Comment by louyuting** [comment]
Dynamic data source is recommended.

**Comment by LargeOrange** [comment]
怎么接入呢？有对应文档么？

**Comment by codergma** [comment]
So Golang applications can't use a dashboard, right?
