### ISSUE TITLE
Improve code comments

### ISSUE THREAD

**Issue by sczyh30** [alibaba/sentinel-golang#204]
## Issue Description

Type: *improvement*

### Describe what feature you want

The existing comments in sentinel-golang were not well-organized and formatted. Some of the generated API documents are ill-formed, like https://pkg.go.dev/github.com/alibaba/sentinel-golang@v0.5.0/core/circuitbreaker?tab=doc

We need to improve existing comments and add more documents for significant code.

**Comment by sczyh30** [comment]
Refer https://blog.golang.org/godoc

**Comment by sczyh30** [comment]
Related to #110

**Comment by louyuting** [comment]
Closed B/C 1.0 Release
