### ISSUE TITLE
[feature]check code format

### ISSUE THREAD

**Issue by yunfeiyanggzq** [alibaba/sentinel-golang#212]
## Issue Description

Type: *feature request*

### Describe what feature you want
我们可以在CI中检测代码的格式，增加go fmt和go import检测，提升代码质量,类似于这样
![图片](https://user-images.githubusercontent.com/43897640/91116662-696b4080-e6bf-11ea-97d4-f8f314db2f13.png)

**Comment by yunfeiyanggzq** [comment]
@sczyh30 please cc

**Comment by louyuting** [comment]
Currently, CI [https://github.com/alibaba/sentinel-golang/blob/master/.travis.yml](https://github.com/alibaba/sentinel-golang/blob/master/.travis.yml)
had add go fmt and go imports checking.

**Comment by yunfeiyanggzq** [comment]
> 
> 
> Currently, CI https://github.com/alibaba/sentinel-golang/blob/master/.travis.yml
> had add go fmt and go imports checking.

我怎么感觉有些没有检测到，这是另一个golang社区格式检测的配置，可以参考下。https://github.com/dragonflyoss/Dragonfly/blob/master/.circleci/config.yml

**Comment by louyuting** [comment]
PR: https://github.com/alibaba/sentinel-golang/pull/170  is tracking this issue.
