### ISSUE TITLE
support for getting the load.Avg() in Windows

### ISSUE THREAD

**Issue by sanxun0325** [alibaba/sentinel-golang#294]
## Issue Description
github.com/alibaba/sentinel-golang depends on github.com/shirou/gopsutil, but the load.Avg() method of it is not implemented on windows

Type: *feature request*

### Describe what feature you want
support for getting the load.Avg() in Windows.

**Comment by sanxun0325** [comment]
You can assign the task to me

**Comment by liqiangz** [comment]
Refer to https://github.com/giampaolo/psutil/pull/1485/files

**Comment by sanxun0325** [comment]
I'm looking at this PR:https://github.com/shirou/gopsutil/pull/977/files

**Comment by louyuting** [comment]
All of these PR  merged. Maybe we need to upgrade this dependency
