### ISSUE TITLE
Support stat bucket number of circuit breaker

### ISSUE THREAD

**Issue by luckyxiaoqiang** [alibaba/sentinel-golang#334]
## Issue Description

Type: *feature request*

### Describe what feature you want
CircuitBreaker中支持指标Bucket数量的配置，以实现更细粒度的指标统计滚动，实现更精细的熔断控制。

### Additional context
目前CircuitBreaker的实现中，指标统计底层使用的是LeapArray，但LeapArray的Sample Count都固定设置为1（即Bucket数量），该方式没有充分利用LeapArray的特性，且一定程度上弱化了指标统计的平滑效果，最终也一定程度地弱化了CircuitBreaker的控制能力。
我们以项目中的example/circuitbreak/error_count示例来简单说明一下。示例规则：
```go
{
   Resource:         "abc",
   Strategy:         circuitbreaker.ErrorCount,
   RetryTimeoutMs:   3000,
   MinRequestAmount: 10,
   StatIntervalMs:   5000,
   Threshold:        50,
},
```
该规则期望的控制行为是5秒内错误数超过50时，触发熔断。
目前的实现5s内只有一个Bucket来记录指标，每隔5s会生成新的Bucket并重新开始记录指标。
我们考虑以下假设场景，第一个时间窗口是[0s, 5s)，第二个时间窗口为[5s, 10s)。
假设[0s, 4s)内没有请求，[4s, 5s)内有49个请求并全部错误，由于[0s, 5s)这个指标统计窗口内错误数没有超过阈值，所以不会触发熔断。
到第5s时，会生成新的Bucket，指标清零。
假设[5s, 6s)有49个请求并全部错误，[6s, 10s)内没有请求，由于[5s, 10s)内指标统计窗口内错误数没有超过阈值，所以不会触发熔断。
但从全局来看[3s, 8s) 这5秒窗口内总共有98个请求且全部错误，超过了阈值，按期望应该触发熔断。

业界相关领域内比较成熟的项目中，对于Circuit Breaker的配置都支持Bucket数量配置，如[resilience4j](https://resilience4j.readme.io/docs/circuitbreaker)、[hystrix](https://github.com/Netflix/Hystrix/wiki/Configuration#metrics)。  
resilience4j中slidingWindowSize即控制滑动窗口中Bucket的数量，不过，resilience4j每个Bucket时间跨度固定为1s。  
hystrix中通过rollingStats.timeInMilliseconds、rollingStats.numBuckets控制滑动窗口，前者为滑动窗口时长，后者为窗口内Bucket的数量，且要求前者必须是后者的整数倍，即保证每个Bucket的时间跨度相等。

基于上述描述，建议在Sentinel-golang CircuitBreaker中支持指标Bucket数量的配置，以实现更细粒度的指标统计滚动，实现更精细的熔断控制。

**Comment by louyuting** [comment]
refer :https://github.com/alibaba/sentinel-golang/pull/338
