### ISSUE TITLE
Add unit test for metric log 

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#38]
## Issue Description

Type: *feature request*

Add metric log unit test

### Describe what feature you want
Code path: core/log/metric/*
Target coverage: 80+% statements.

**Comment by zsy619** [comment]
I will try to do some work on this issue. Please assign it to me.

**Comment by louyuting** [comment]
Nice. Contribution are welcomed.

**Comment by louyuting** [comment]
PR had been closed
