### ISSUE TITLE
this project not can use java console

### ISSUE THREAD

**Issue by huarong8** [alibaba/sentinel-golang#397]
这个项目不能使用java的控制台
this project can not use java console
生产环境需要有监控
product environment needs monitor
希望能有接入java控制台的功能
Hope to have access to the Java console feature

**Comment by sczyh30** [comment]
Hi, the dashboard integration is not planned yet. It's recommended to use metric exporter to integrate with external monitoring systems.

**Comment by huarong8** [comment]
ok, thanks
