### ISSUE TITLE
[BUG] When use Nacos as datasource, no rule config will cause error.

### ISSUE THREAD

**Issue by brotherlu-xcq** [alibaba/sentinel-golang#400]
## Issue Description

Type: *bug report*

### Describe what happened
Run the datasource_nacos_example.go without configurer the rule in Nacos.
the will meet the error below:
![image](https://user-images.githubusercontent.com/25661357/114872250-b6f21480-9e2c-11eb-9ad6-36993d7c6c8c.png)

### Describe what you expected to happen
The example can run without configurer rule.

### How to reproduce it (as minimally and precisely as possible)

1. Run the datasource_nacos_example.go without configurer the rule in Nacos.

**Comment by brothelul** [comment]
reference the issue in Nacos [209] (https://github.com/nacos-group/nacos-sdk-go/issues/209)

**Comment by brothelul** [comment]
Maybe we need upgrade the nacos-sdk in the future.

**Comment by sanxun0325** [comment]
@brothelul Yes, I'll follow up on this
