### ISSUE TITLE
what does the reset() of MetricBucket do? seems no references

### ISSUE THREAD

**Issue by titanxxh** [alibaba/sentinel-golang#403]
https://github.com/alibaba/sentinel-golang/blob/c362aaeafd1e500c9812d4961bcea81b25008b45/core/stat/base/metric_bucket.go#L68

another question:
the minrt updating function is not thread safe.
```go
func (mb *MetricBucket) AddRt(rt int64) {
	mb.addCount(base.MetricEventRt, rt)
	if rt < atomic.LoadInt64(&mb.minRt) { // here is not thread safe.
		// Might not be accurate here.
		atomic.StoreInt64(&mb.minRt, rt)
	}
}
```

**Comment by sczyh30** [comment]
> what does the reset() of MetricBucket do? seems no references

This was designed for refreshing the deprecated bucket (i.e. `ResetBucketTo` of BucketGenerator) but not used (maybe forgotten). Would you like to submit a PR to improve it?

**Comment by Howie59** [comment]
i can do this in my spare time

**Comment by Alipebt** [comment]
@sczyh30 I think you mean that the existing reset() function is not being used and a new MetricBucket is recreated in the ResetBucketTo() function. Therefore, you want to optimize your code to call reset() to avoid this unnecessary operation. Is that so?

**Comment by sczyh30** [comment]
> @sczyh30 I think you mean that the existing reset() function is not being used and a new MetricBucket is recreated in the ResetBucketTo() function. Therefore, you want to optimize your code to call reset() to avoid this unnecessary operation. Is that so?

Yeah, that's it.
