### ISSUE TITLE
[Feature] Circuit breaker half-open probe strategy | 熔断half-open恢复时支持配置探测次数

### ISSUE THREAD

**Issue by brzyangg** [alibaba/sentinel-golang#411]
看wiki文档中描述:
> Half-Open 状态：半开状态，该状态下除了探测流量，其余对资源的访问也会被切断。探测流量指熔断器处于半开状态时，会周期性的允许一定数目的探测请求通过，如果探测请求能够正常的返回，代表探测成功，此时熔断器会重置状态到 Closed 状态，结束熔断；如果探测失败，则回滚到 Open 状态。

会允许一定数目的探测请求通过，但是我看代码中：

```
        if curStatus == HalfOpen {
		if err == nil {
			b.fromHalfOpenToClosed()
			b.resetMetric()
		} else {
			b.fromHalfOpenToOpen(1.0)
		}
		return
	}
 ```

处于半开状态时，一次请求，成功或者失败，就会转换状态。
请问这块的逻辑是如我看到的这样只判断接下来一次请求的状态还是？

**Comment by sczyh30** [comment]
The probe strategy of half-open state is single-probe in current version. Contributions are welcomed.

---

目前的实现还是单次探测，欢迎社区一起来完善这一块。

**Comment by sanxun0325** [comment]
是不是可以考虑，对于熔断规则 增加一个 探测次数的参数。 当断路器打开并且进入周期探测时 对请求数进行累加。

1. 如果在累加过程中有请求失败 则断路器由半开状态变为打开。
2. 如果在到达探测次数并且没有请求失败，则断路器变为关闭状态并清空统计指标。

**Comment by sczyh30** [comment]
Resolved via #428
