### ISSUE TITLE
rule_manager.go的LoadRules中，currentRules和resRulesMap是如何保证切片中的rule顺序是一致的？

### ISSUE THREAD

**Issue by muyoucun557** [alibaba/sentinel-golang#446]
两个map[string]slice如果是deep equal的话，那么切片中元素必须是deep equal的。
元素相同，但是顺序不同的两个切片不是deep equal的，例如[]{1,2,3} is not deep equal []int{1,3,2}。
currentRules和resRulesMap如果是deep equal的话，那么必须保证切片中rule是相同的，且顺序是相同的。
resRulesMap中slice的rule顺序和LoadRules传入的参数的rule顺序是有关的，目前来看，currentRules和resRulesMap中slice的rule顺序是无法保证一只的，那么
```
isEqual := reflect.DeepEqual(currentRules, resRulesMap)
	if isEqual {
		logging.Info("[Flow] Load rules is the same with current rules, so ignore load operation.")
		return false, nil
	}
```
是无意义的。哪位老哥能解答一下，谢谢

**Comment by sanxun0325** [comment]
是的，这里是有优化空间的。正常情况下 配置规则的文件不改变顺序的情况， rules slice是不会改变顺序的。 但是也存在rule的顺序改变，但是内容没变。这里也会重新加载一次规则。不过不会消耗过多资源 影响不大。

**Comment by muyoucun557** [comment]
> 是的，这里是有优化空间的。正常情况下 配置规则的文件不改变顺序的情况， rules slice是不会改变顺序的。 但是也存在rule的顺序改变，但是内容没变。这里也会重新加载一次规则。不过不会消耗过多资源 影响不大。

@sanxun0325 👌
