### ISSUE TITLE
Add unit test for flow control

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#45]
## Issue Description

Type: *feature request*
Add unit test for flow control

### Describe what feature you want
Code path: core/flow/*
Target coverage: 50+% statements.

**Comment by zsy619** [comment]
好的，领取了

**Comment by louyuting** [comment]
Welcomed~

**Comment by zsy619** [comment]
@louyuting 
1、帮忙看下是哪里问题，在本机测试没有问题
2、以前提交的commit在本PR中
![image](https://user-images.githubusercontent.com/6278792/75422511-b8862200-5977-11ea-87df-7316e8f9feed.png)
红色是本次要合并内容

**Comment by zsy619** [comment]
@louyuting 
Add unit test for flow control #69
出现这个问题，看go.mod也没有github.com/alibaba/sentinel-golang这个引用

go: github.com/alibaba/sentinel-golang/core/flow tested by
	github.com/alibaba/sentinel-golang/core/flow.test imports
	github.com/sentinel-group/sentinel-golang/core/base: github.com/sentinel-group/sentinel-golang@v0.0.0-20200227055908-d7b7e665cbff: parsing go.mod:
	module declares its path as: github.com/alibaba/sentinel-golang
	        but was required as: github.com/sentinel-group/sentinel-golang

**Comment by louyuting** [comment]
Now, this project use the module name “github.com/alibaba/sentinel-golang”.
You might need to update  the newest code.

**Comment by louyuting** [comment]
Related PR had been closed.
