### ISSUE TITLE
Does GetSum include the current bucket? | flow中的DoCheck方法，判断当前周期内的请求数量是否超过阈值是否少算了当前bucket的请求数量？

### ISSUE THREAD

**Issue by muyoucun557** [alibaba/sentinel-golang#452]
```Go
func (d *RejectTrafficShapingChecker) DoCheck(resStat base.StatNode, batchCount uint32, threshold float64) *base.TokenResult {
	metricReadonlyStat := d.BoundOwner().boundStat.readOnlyMetric
	if metricReadonlyStat == nil {
		return nil
	}
	curCount := float64(metricReadonlyStat.GetSum(base.MetricEventPass))
	if curCount+float64(batchCount) > threshold {
		msg := "flow reject check blocked"
		return base.NewTokenResultBlockedWithCause(base.BlockTypeFlow, msg, d.rule, curCount)
	}
	return nil
}
```
```
curCount := float64(metricReadonlyStat.GetSum(base.MetricEventPass))
```
其中的GetSum方法应该计算“当前以bucket为结尾bucket的周期内的请求总数”，但是我看源码中实现的是：去掉了当前bucket的请求数，只计算了前面sampleCount-1个bucket的请求数量。
请问这是怎么回事？哪位老哥能帮我解答一下困惑。

**Comment by sczyh30** [comment]
做 check 的时候，这里面其实就是取的以当前 bucket 为结尾的时间窗口周期。注意 `ValuesConditional` 是拿 bucketStart 作为过滤条件的。

Here we filter out these buckets, the last of which is actually *the current bucket*:

https://github.com/alibaba/sentinel-golang/blob/ea8c74ff026a264e19ac48fa659975fd7e787030/core/stat/base/sliding_window_metric.go#L58-L63

https://github.com/alibaba/sentinel-golang/blob/ea8c74ff026a264e19ac48fa659975fd7e787030/core/stat/base/sliding_window_metric.go#L108-L114

**Comment by muyoucun557** [comment]
> 做 check 的时候，这里面其实就是取的以当前 bucket 为结尾的时间窗口周期。注意 `ValuesConditional` 是拿 bucketStart 作为过滤条件的。
> 
> Here we filter out these buckets, the last of which is actually _the current bucket_:
> 
> https://github.com/alibaba/sentinel-golang/blob/ea8c74ff026a264e19ac48fa659975fd7e787030/core/stat/base/sliding_window_metric.go#L58-L63
> 
> https://github.com/alibaba/sentinel-golang/blob/ea8c74ff026a264e19ac48fa659975fd7e787030/core/stat/base/sliding_window_metric.go#L108-L114

感谢老哥的回复。

您看下面的代码
func (m *SlidingWindowMetric) getBucketStartRange(timeMs uint64) (start, end uint64) {
	curBucketStartTime := calculateStartTime(timeMs, m.real.BucketLengthInMs())
	end = curBucketStartTime
	start = end - uint64(m.intervalInMs) + uint64(m.real.BucketLengthInMs())
	return
}

// 计算出的是当前时间前一个桶的结尾时间
func calculateStartTime(now uint64, bucketLengthInMs uint32) uint64 {
	return now - (now % uint64(bucketLengthInMs))
}

|----------|----------|----------|
                                   ^           ^
                                end          ^
                                                ^
                                              now

**Comment by binbin0325** [comment]
实际上在计算出start和end后，会根据格子的开始时间与start和end进行匹配。
如下图所示：统计间隔=1000ms（跨两个格子），now=1300时 计算出start=500,end=1000, 

<img width="668" alt="image" src="https://user-images.githubusercontent.com/28588342/192133229-881ee595-eed5-4b21-9dba-a9835b1db7eb.png">

那么在计算sum时，会根据如下条件遍历格子，也就会找到开始时间是500和1000的两个格子，那么统计的时候1000的这个格子中的数据自然也会被统计到。（当前时间1300，在1000的这个格子中）
```golang
	satisfiedBuckets := m.real.ValuesConditional(now, func(ws uint64) bool { 
 		return ws >= start && ws <= end 
 	}) ```
