### ISSUE TITLE
Add unit test for statistic module

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#46]
## Issue Description

Type: *feature request*
Add unit test for statistic module

### Describe what feature you want
Code path: core/stat/*
Target coverage: 80+% statements.

**Comment by hellosmallstone** [comment]
I will try to do some work on this issue. Please assign it to me.

**Comment by louyuting** [comment]
> I will try to do some work on this issue. Please assign it to me.

Nice.

**Comment by louyuting** [comment]
PR had been closed
