### ISSUE TITLE
Flow control doc typo (CN) | 中文文档文字错误

### ISSUE THREAD

**Issue by chinaran** [alibaba/sentinel-golang#462]
https://sentinelguard.io/zh-cn/docs/golang/flow-control.html
<img width="903" alt="image" src="https://user-images.githubusercontent.com/3775544/160085413-bae17aff-3c97-4dd4-8d54-325cf77bf29b.png">

**Comment by sczyh30** [comment]
Would you like to contribute a PR to fix the typo? Source doc: https://github.com/sentinel-group/sentinel-website/blob/master/docs/zh-cn/golang/Flow-Control.md

**Comment by chinaran** [comment]
@sczyh30 Please check this PR: https://github.com/sentinel-group/sentinel-website/pull/41

**Comment by sczyh30** [comment]
Resolved in https://github.com/sentinel-group/sentinel-website/pull/41
