### ISSUE TITLE
Doc mismatch for fields in metric log | 监控日志文档里的字段数量和实际日志列不符

### ISSUE THREAD

**Issue by why444216978** [alibaba/sentinel-golang#479]
https://github.com/alibaba/sentinel-golang/wiki/%E5%AE%9E%E6%97%B6%E7%9B%91%E6%8E%A7#%E7%A7%92%E7%BA%A7%E7%9B%91%E6%8E%A7%E6%97%A5%E5%BF%97

我看上述文档里的日志字段是 8 列，但是实际运行打印的日志是 11 列（1660101595000|2022-08-10 11:19:55|abc|12|134|12|3|53|0|2|0），辛苦更新一下文档或回复描述一下最新的日志列含义，感谢🙏

**Comment by sczyh30** [comment]
Hi, we've updated the wiki doc. Thanks for reporting.
