### ISSUE TITLE
Support rate limiting by origin group | 请求支持limitApp的能力，像java一样

### ISSUE THREAD

**Issue by qshuai** [alibaba/sentinel-golang#491]
根据不同请求来源进行分组，不同分组的流控规则可以设置的不同。
目前看sentinel-golang还没有这样的能力，请求支持。

如果有hacking的设置方式，能帮忙提供一下吗

**Comment by sczyh30** [comment]
建议将请求来源作为参数传入埋点，然后使用热点参数流控规则即可：https://sentinelguard.io/zh-cn/docs/golang/hotspot-param-flow-control.html

---

It's recommended to leverage *parameter flow control* to achieve this. Go docs: https://pkg.go.dev/github.com/alibaba/sentinel-golang@v1.0.4/core/hotspot#Rule

**Comment by sczyh30** [comment]
Any further questions?

**Comment by qshuai** [comment]
我如果把请求来源作为资源名称的一部分，是否推荐这种方式。

**Comment by binbin0325** [comment]
资源名称可以是任何字符，根据你的业务需要构建就行，sentinel-go不会限制。

**Comment by qshuai** [comment]
好的，多谢
