### ISSUE TITLE
[Development environment]submodule import package failed in IDE 导入到IDE中子模块报错

### ISSUE THREAD

**Issue by honganan** [alibaba/sentinel-golang#492]
请教一下项目该如何配置开发环境，我在导入IDE执行go mod tidy后最外层go.mod没有问题但是里面每个子模块的依赖都有部分报错，项目是怎么管理依赖的？

**Comment by binbin0325** [comment]
@honganan 每个子某模块都是独立的module， 在需要更新依赖的子模块的go.mod目录中，go mod tidy就可以了

**Comment by honganan** [comment]
好的，如果没有更好的方式，目前这样也能解决问题，那我把 issue 关闭了
