### ISSUE TITLE
Kubernetes CRD data source

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#50]
## Issue Description

Type: *feature request*
Investigate the feasibility of adapting Sentinel to the cloud native

### Describe what feature you want
Need detail investigation document.

**Comment by sczyh30** [comment]
Related PR: https://github.com/sentinel-group/sentinel-go-datasource-k8s-crd/pull/1

**Comment by sczyh30** [comment]
Refer: https://github.com/sentinel-group/sentinel-go-datasource-k8s-crd
