### ISSUE TITLE
Add etcd data-source extenstion

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#51]
## Issue Description

Type: *feature request*
Adapt etcd as dynamic datasource  for Sentinel

### Describe what feature you want
Need detail design.
PR

**Comment by zsy619** [comment]
从etcd获取sentinel配置信息？

**Comment by louyuting** [comment]
No, the etcd ACTS as a dynamically configured data center.
You can refer to https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95

**Comment by wenxuwan** [comment]
If there don't have people take it, i can do it.

**Comment by louyuting** [comment]
Nice~
Contribution are welcomed.

**Comment by louyuting** [comment]
> If there don't have people take it, i can do it.

The issue had been assigned to you.

**Comment by louyuting** [comment]
If you have good idea, discussion are welcomed.

**Comment by wenxuwan** [comment]
> If you have good idea, discussion are welcomed.

ok, when i finish the design,  i will talk with guys in Dingding group.

**Comment by louyuting** [comment]
Nice

**Comment by sczyh30** [comment]
FYI: the counterpart in Java (just for reference): https://github.com/alibaba/Sentinel/tree/master/sentinel-extension/sentinel-datasource-etcd

**Comment by wenxuwan** [comment]
The feature will start after the datasource frame work design finished.

**Comment by sczyh30** [comment]
> The feature will start after the datasource frame work design finished.

Hi, you may refer to the basic design in #73. We'll update the document later.

**Comment by louyuting** [comment]
> > The feature will start after the datasource frame work design finished.
> 
> Hi, you may refer to the basic design in #73. We'll update the document later.

FYI @gorexlv  Discussions are welcomed

**Comment by louyuting** [comment]
Refer to datasource design: 
[https://github.com/alibaba/sentinel-golang/wiki/Dynamic-DataSource-Extension-Framework-Design](https://github.com/alibaba/sentinel-golang/wiki/Dynamic-DataSource-Extension-Framework-Design)
