### ISSUE TITLE
请问下有go版本的 sentinel-dashboard实现吗？

### ISSUE THREAD

**Issue by yejialiango** [alibaba/sentinel-golang#522]
## Issue Description

Type: *feature request*

**Comment by jnan806** [comment]
没有

**Comment by yejialiango** [comment]
老哥你们有计划支持吗？多语言版的分布式限流服务

**Comment by sczyh30** [comment]
Dashboard 和分布式流控（集群流控）不是一个东西哈，前者 Sentinel Go 暂无计划支持，后者 refer https://github.com/alibaba/sentinel-golang/issues/76

**Comment by yejialiango** [comment]
ok，明白了，多谢
