### ISSUE TITLE
Add integration module for dubbo-go

### ISSUE THREAD

**Issue by louyuting** [alibaba/sentinel-golang#55]
## Issue Description

Type: *feature request*

### Describe what feature you want
Add integration module for [dubbo-go](https://github.com/apache/dubbo-go) client and server.

### Additional context

Discussions are welcomed!

**Comment by pantianying** [comment]
dubbo-go  provides a filter mechanism, which makes it easy to set a custom filter. We just need to implement the following filter interface：
![image](https://user-images.githubusercontent.com/20589945/74914265-1c9b6a00-53fd-11ea-842c-b661a527ef76.png)
并且在config.Load()函数之前调用 ' SetFilter(name string, v func() filter.Filter) '函数，即可将filter实例划到filter库中。

**Comment by sczyh30** [comment]
Resolved via #60.
