### ISSUE TITLE
util/time.go 方法参数重命名并添加参数注释

### ISSUE THREAD

**Issue by zsy619** [alibaba/sentinel-golang#63]
## Issue Description

Type: feature request

### Describe what feature you want

给FormatTimeMillis参数重命名并添加注释
给FormatDate添加注释

### Additional context

![1582601608577](https://user-images.githubusercontent.com/6278792/75213205-605aee80-57c4-11ea-81f3-b9d7052f1bb7.jpg)

**Comment by sczyh30** [comment]
Contributions are welcomed!
