### ISSUE TITLE
Implement Datasource And PropertyListener

### ISSUE THREAD

**Issue by gorexlv** [alibaba/sentinel-golang#74]
## Issue Description

1. Implement DatasourceExtension and PropertyListener
2. Multiple configuration formats are supported 

Type: *feature request*

### Describe what feature you want

if possible, avoid passing` interface{}` in Rule converter function, same or like this:

``` golang
// *_rule_manager.go
func Convert(data interface{}) error {
        config := data.([]byte)
        // convert config to FlowRule/SystemRule
}
```

which is not elegant and maybe not friendly for multiple configuration format.

**Comment by gorexlv** [comment]
duplicated with #58

**Comment by louyuting** [comment]
> duplicated with #58

Yes, I will close this issue.
We could discuss under #58 
Discussion are welcomed.
