### ISSUE TITLE
generate mocks for interface automation

### ISSUE THREAD

**Issue by hellosmallstone** [alibaba/sentinel-golang#79]
## Issue Description
While doing unit tests, we usually need to use mock functions. In the current project, mock codes seem to be implemented manually, such as StatNodeMock in core/base/stat_test.go, MetricItemRetrieverMock in core/log/metric/aggregator_test.go, and so on. 
As the project progresses, more and more mock functions will be available. To improve efficiency, we can consider automatically generating mock functions, by using mockery(https://github.com/vektra/mockery).

Type: *feature request*

### Describe what feature you want
By running "go generate", we can get all mocks for all interfaces to be tested.

### Additional context
I found this while solving issue 46, and prepare to implement the test function based on the new mock function.

**Comment by louyuting** [comment]
Contributions and Discussions are welcomed.

**Comment by hellosmallstone** [comment]
In the core/base/stat_test.go file, we define struct StatNodeMock as the mock of StatNode interface. And in the core/base/slot_chain_test.go file, function TestSlotChain_Entry_With_Panic uses this mock as follows: 
        **statNodeMock := &StatNodeMock{}
	statNodeMock.On("AddErrorRequest", mock.Anything).Return()
	ctx.StatNode = statNodeMock**
If we use the mockery to generate mocks for StatNode interface, we just need to add "//go:generate mockery -dir . -name StatNode -case underscore -output mocks/" to the defintion of StatNode and the mocks will be auto-generated in the "mocks" folder, which is similar to StatNodeMock. The generated mocks are as follows:
    **package mocks

    import mock "github.com/stretchr/testify/mock"

    // StatNode is an autogenerated mock type for the StatNode type
    type StatNode struct {
	    mock.Mock
    }
    ..........** 
The function TestSlotChain_Entry_With_Panic will be changed into:
        **statNodeMock := &mocks.StatNode
	statNodeMock.On("AddErrorRequest", mock.Anything).Return()
	ctx.StatNode = statNodeMock**
Only the definition has been changed, but the usage has not been changed.

What do you think about this? @louyuting @sczyh30

**Comment by gorexlv** [comment]
How about `github.com/golang/mock`?

**Comment by louyuting** [comment]
Nice idea, looking forward to your PR.

**Comment by hellosmallstone** [comment]
> How about `github.com/golang/mock`?

According to the official introduction of mockery, it removes the boilerplate coding required to use mocks.  I personally feel that mockery is simpler and easier to use.

**Comment by hellosmallstone** [comment]
In the process of solving this issue, I encountered the following problems, and need everyone to discuss it.

The mocks's files are usually located in a separate subdirectory of the mocked interface file's directory, such as "mocks". When the function's input or output parameters's type is defined in the current package, the mocks's package will import the interface's package. For example in core/base/stat.go: 
```
package base

type WriteStat interface {
	AddMetric(event MetricEvent, count uint64)
}
```
The mocks file of WriteStat interface imports "base" package, and is as follows:
```
package mocks

import base "github.com/alibaba/sentinel-golang/core/base"

type WriteStat struct {
	mock.Mock
}

func (_m *WriteStat) AddMetric(event base.MetricEvent, count uint64) {
	_m.Called(event, count)
}
```
While writing test units for "AddMetric" function, the file imports this mocks package and is as follows:
```
package base

import base "github.com/alibaba/sentinel-golang/core/base/mocks"

func Testxxxxx(){
    ws := &mocks.WriteStat{}
}

```
This file will produce "import cycle" problem, which is not allowed in golang. 

Should we put the structure definition into a common package to avoid this problem?
This change affects many source files and may require unified planning.

**Comment by hellosmallstone** [comment]
If we put the structure definition into a common package to avoid "import cycle" problem, many files used these structure must be modified and import the new package. However, in the current situation, mock is not used frequently in unit tests. A lot of changes won't make sense.
Therefore, I close this issue and we can open this problem again if there is a need in the future.
